version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.7-buster
    working_directory: ~/PySaber
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python ./tests/test.py test
          name: Tests

workflows:
  main:
    jobs:
      - build
