version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  dependencies:
    executor: python/default
    working_directory: ~/PySaber
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: sudo pip install requirements.txt
          name: Install Dependencies
  build:
    steps:
      - run:
          command: |
            python ./tests/test.py test

workflows:
  main:
    jobs:
      - dependencies
      - build
